apps/historial/urls.py
from django.conf.urls import url
from apps.historial.views import historial_view, historial_list,historial_pac,informe_historial_pac
from django.contrib.auth.decorators import login_required
app_name='historial'
urlpatterns = [
    url(r'^agregar',login_required(historial_view), name='agregar_historial'),
    url(r'^listar',login_required(historial_list), name='listar_historial'),
    url(r'^listar/(?P<ci>\d+)/$',login_required(historial_pac), name='historia_paciente'),
    url(r'^paciente/(?P<ci>\d+)/$',login_required(historial_pac), name='historia_paciente_x'),
    url(r'^informe/(?P<ci>\d+)/$',login_required(informe_historial_pac), name='informe_paciente'),
]

apps/medico/urls.py
from django.conf.urls import url
from apps.medico.views import medico_list,agregar_medico
from django.contrib.auth.decorators import login_required
app_name='medico'
urlpatterns = [
    url(r'^listar$', medico_list, name='listar_medico'),
    url(r'^registrar',login_required(agregar_medico), name="registrarm"),
]

apps/paciente/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.paciente.views import paciente_list, paciente_edit, paciente_elim,agregar_paciente
app_name = "paciente"
urlpatterns = [
    url(r'^listar$', login_required(paciente_list), name='listar_paciente'),
    url(r'^editar/(?P<ci>\d+)/$',login_required(paciente_edit), name='editar_paciente'),
    url(r'^eliminar/(?P<ci>\d+)/$',login_required(paciente_elim), name='eliminar_paciente'),
    url(r'^registrar',login_required(agregar_paciente), name="registrar")
]

proyect/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.paciente import views
from apps.historial.views import historial_list
from apps.paciente import urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


app_name='inicio'
urlpatterns=[
    url(r'^accounts/login/', auth_views.LoginView.as_view(template_name='index.html'), name="login"),
    url(r'^$', auth_views.LoginView.as_view(template_name='index.html'), name="login"),
    url(r'^admin/', admin.site.urls),
    url(r'^sesion/', views.inicio, name='inicio'),
    url(r'^historial/', include('apps.historial.urls', namespace='historial')),
    url(r'^paciente/', include('apps.paciente.urls', namespace='paciente')),
    url(r'^medico/', include('apps.medico.urls', namespace='medico')),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='index.html'), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Informe_historial_paciente.html
{% load static %}
<html>
<head>
	<title>Informe</title>
	  <link rel="stylesheet" type="text/css" href={% static 'css/estilos.css' %}>
</head>
<body>

	<div class="contenedor">
		<div class="principal">
{% if paciente %}
        {% for paciente in paciente %}
			<div class="nombre">
				<p><h2>HISTORIAL DEL PACIENTE<h2></p>
				<p><h2>{{ paciente.first_name }} {{ paciente.last_name }} </h1></p>

			</div>
			<div class="header">
				<div class="row1" >
					<div class="esp">
						<img src="{{ paciente.foto.url }}" height=150px>
					</div>

					<div class="esp">
						<p><b>CI:</b>{{ paciente.ci}}</p>
						<p><b>Fecha Nacimiento:</b>{{paciente.fecha_naci}}</p>
						<p><b>Email:</b>{{paciente.email}}</p>
						<p><b>telefono:</b>{{ paciente.telefono}}</p>
					</div>
				</div>
			</div>
        {% endfor %}
{% endif %}
		</div>
        {% if historiales %}
		{% for historial in historiales %}
		<div class="cuerpo">
				<div class="contenido">
					<h2 class="titulo">Nro Historial: {{historial.nrohistoria}}</h2>
					<p><b><h3>Medico:</h3></b>      Dr.{{historial.medico.first_name}} {{historial.medico.last_name}}</p>
					<p><b>Fecha y Hora:</b>{{historial.hora}}</p>
					<p><b>Caracteristicas:</b></p>
					<p>{{historial.caracteristica}}</p>
					<p><b>Diagnostico:</b> {{historial.diagnostico}}</p>
					<p><b>Receta Medica :</b>{{historial.receta}}</p>
				</div>
		</div>
		{% endfor %}
		{% else %}
        	<h1 align="center"> NO HAY REGISTROS</h1>
    	{% endif %}
	</div>



</body>
</html>

templates/agregar_historial.html
{% extends 'base0.html' %}


{% block content %}
<div class="container">
    <h4 align="CENTER">AGREGAR HISTORIAL</h4>

    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Guardar</button>
    </form>

</div>
{% endblock %}

templates/agregar_paciente.html
{% extends "base0.html" %}
{% block content %}
<div class="container">
    <h4 align="CENTER">AGREGAR PACIENTE</h4>

    <form method="POST" action=""  cenctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
 <p> ingresar foto {{ form.foto }}</p>

    <button type="submit">Guardar</button>
    </form>

</div>
{% endblock %}

templates/barranav.html
 <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'login' %}">Inicio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'medico:listar_medico' %}">Personal Medico <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.miregion.org/BO/La-Paz/Provincia-Murillo/Municipio-El-Alto/Spots/Centro-De-Salud-Villa-Tunari/">Ubicacion</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Contacto</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'logout' %}" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">SALIR</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
            <ul class="dropdown-menu" role="menu">
                <li><a class="dropdown-item" href="{% url 'logout' %}">salir</a></li>
            </ul>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
    </form>
  </div>
</nav>

templates/base0.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Centro Salud Villa Tunari</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/jumbotron/">

    {% include "head_css.html" %}

  </head>
  <body>
        {% include "barranav.html" %}
        <main role="main">
    {% block content %}

    {% endblock %}
        </main>
    {% block footer %}
        <footer >
            <p>&copy; Company 2017-2019</p>
        </footer>
    {% endblock %}
  </body>
</html>

templates/contacto.html
{{ titulo }}<br/>
<hr/>
<br/>
<form method="POST" action="">{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Reguistrame' />
</form>

templates/eliminar_paciente.html
{% extends 'base0.html' %}


{% block content %}
<div class="container">
    <h4 align="CENTER">AGREGAR HISTORIAL</h4>

    <form method="POST">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de {{ paciente.nombre }}?</h3>


    <button class="btn btn-primary"  type="submit">Si, Eliminar</button>
    <a class="btn btn-default" href="{% url 'paciente:listar_paciente'%}">Cancelar</a>
    </form>

</div>
{% endblock %}

templates/index.html
<!--heredamos de base0 -->
{% extends "base0.html" %}
{% load static %}

<!-- modificamos el bloque -->
{% block content %}
  <div class="jumbotron" style="background-image:url("{% static 'img/centro.jpg'%}")>
    <div class="container">
      <h1 class="display-3">Centro Salud Villa Tunari</h1>
      <p>El Centro de Salud Villa Tunari del Distrito 4, perteneciente a la Red Lotes y Servicios</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Leer mas &raquo;</a></p>
    </div>
    <div class="container">
        <img class="img-responsive" src="{% static 'img/centro.jpg' %}" style="height: 300px; width: 1050px">
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">

        <div class='col-sm-4 col-xs-12 pull-right'>
	    	<p class='text-aline-center'><h2>Bienvenido</h2></p>

            {% block login %}
            <div class="login">
                <form method="post" >
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <div class="form-group">
                                <label for="username">Nombre de Usuario:</label>
                                <input class="form-control" type="text" name="username">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <div class="form-group">
                                <label for="username">Contraseña: </label>
                                <input class="form-control" type="password" name="password">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <div class="form-group">
                                <a href="#">Olvidé mi contraseña</a>
                                <input class="btn btn-primary" type="submit" value="Ingresar">
                            </div>
                        </div>
                    </div>

                </form>
                </div>
                {% endblock %}

        </div>
      <div class="col-md-4">



        <h2>Informacion</h2>
        <img class="img-responsive" src="{% static 'img/centro1.jpg' %}" style="width: 300px">
        <p>Centro de Salud de Villa Tunari recibe donación de equipos para prevenir el cáncer de cuello uterino. </p>
        <p><a class="btn btn-secondary" href="http://amibolivia.com/AMI/?p=6149" role="button">Leer mas &raquo;</a></p>
      </div>

    <div class="col-md-4">
        <h2>Centro de Salud </h2>
        <img class="img-responsive" src="{% static 'img/exterior.jpg' %}" style="width: 300px">
        <p>parte exterior del centor de salud</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>


    </div>

    <div class="row">
    <div class="col-md-4">
        <h2>Ambientes</h2>
        <img class="img-responsive" src="{% static 'img/centro2.jpg' %}" style="width: 300px">
        <p>el centro de salud cuenta con diferentes Ambientes</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>

  <div class="col-md-4">
        <h2>Ambientes</h2>
        <img class="img-responsive" src="{% static 'img/centro3.jpg' %}" style="width: 300px">
        <p>el centro de salud cuenta con diferentes Ambientes</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>

   <div class="col-md-4">
        <h2>Aviso</h2>
        <img class="img-responsive" src="{% static 'img/aviso.jpg' %}" style="width: 300px">
        <p> el centro de salud informa </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>
    <hr>

  </div> <!-- /container -->
{% endblock %}

templates/listar_historial.html
{% extends 'base0.html' %}

{% block content %}
<div class="container">
<table class="table table-bordered">
    <thead>
        <tr>
            <td>nroHistoria</td>
            <td>paciente</td>
            <td>medico</td>
            <td>fecha y hora</td>
            <td>caracteristica</td>
            <td>diagnostico</td>
            <td>receta</td>
        </tr>
    </thead>
    <tbody>
         {% if historiales %}
         {% for historial in historiales %}
            <tr>
                <td>{{ historial.nrohistoria }}</td>
                <td>{{historial.paciente.ci}}</td>
                <td>{{historial.medico.first_name}}</td>
                <td>{{historial.hora}}</td>
                <td>{{historial.caracteristica}}</td>
                <td>{{historial.diagnostico}}</td>
                <td>{{historial.receta}}</td>
            </tr>
         {% endfor %}
    {% else %}
        <h1 align="center"> NO HAY REGISTROS</h1>
    {% endif %}
    </tbody>
</table>
</div>


{% endblock %}

templates/listar_historialpac.html
{% extends 'base0.html' %}

{% block content %}
<table class="table table-bordered">
    <thead>
        <tr>
            <td>nroHistoria</td>
            <td>paciente</td>
            <td>medico</td>
            <td>hora</td>
            <td>caracteristica</td>
            <td>diagnostico</td>
            <td>receta</td>
        </tr>
    </thead>
    <tbody>
         {% if historialp %}
         {% for historial in historialp %}
            <tr>
                <td>{{historial.nrohistoria }}</td>
                <td>{{historial.paciente.first_name}}{{ historial.paciente.last_name }}</td>
                <td>{{historial.medico.first_name}}{{ historial.paciente.last_name }}</td>
                <td>{{historial.hora}}</td>
                <td>{{historial.caracteristica}}</td>
                <td>{{historial.diagnostico}}</td>
                <td>{{historial.receta}}</td>
            </tr>
         {% endfor %}
    {% else %}
        <h1 align="center"> NO HAY REGISTROS</h1>
    {% endif %}
    </tbody>
</table>

{% endblock %}

templates/listar_medico.html
{% extends 'base0.html' %}
{% block content %}
<div class="container">
<h1 align="center"> LISTA DE MEDICOS</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>FOTO</td>
            <td>ID</td>
            <td>NOMBRE</td>
            <td>APELLIDOS</td>
            <td>AREA</td>
            <td>ESPECIALIDAD</td>
            <td>EMAIL</td>
        </tr>
    </thead>
    <tbody>
         {% if medicos %}
         {% for medico in medicos %}
            <tr>
                <td><img src="{{ medico.foto.utl }}" style="width: 100px">  </td>
                <td>{{ medico.id_medico }}</td>
                <td>{{medico.first_name}}</td>
                <td>{{medico.last_name}}</td>
                <td>{{medico.area}}</td>
                <td>{{medico.especialidad}}</td>
                <td>{{medico.email}}</td>
            </tr>
         {% endfor %}
    {% else %}
        <h1 align="center"> NO HAY MEDICOS REGISTRADOS</h1>
    {% endif %}
    </tbody>
</table>
</div>
{% endblock %}

templates/listar_paciente.html
{% extends 'base0.html' %}
{% load static %}
{% block content %}
<div class="container">
<h1 align="center"> LISTA DE PACIENTES</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>FOTO</td>
            <td>CI</td>
            <td>NOMBRE</td>
            <td>APELLIDO</td>
            <td>FECHA NACIMIENTO</td>
            <td>EMAIL</td>
            <td>TELEFONO</td>
            <td>ACCIONES</td>
            <td>CODIGO QR</td>
        </tr>
    </thead>
    <tbody>
         {% if pacientes %}
         {% for paciente in pacientes %}
            <tr>
                <td> <img src="{{ paciente.foto.url }}" style="width: 100px"></td>
                <td>{{ paciente.ci }}</td>
                <td>{{paciente.first_name}}</td>
                <td>{{paciente.last_name}}</td>
                <td>{{paciente.fecha_naci}}</td>
                <td>{{paciente.email}}</td>
                <td>{{paciente.telefono}}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'paciente:editar_paciente' paciente.ci%}">Editar</a>
                     <a class="btn btn-primary" href="{% url 'paciente:eliminar_paciente' paciente.ci%}">Eliminar</a>
                </td>
                <td>  <img src="{{ paciente.codigoqr.url }}" style="width: 100px"></td>
            </tr>
         {% endfor %}
    {% else %}
        <h1 align="center"> NO HAY PACIENTES</h1>
    {% endif %}

    </tbody>
</table>
</div>
{% endblock %}

templates/login.html
<!--heredamos de base0 -->
{% extends "base0.html" %}
{% load static %}

<!-- modificamos el bloque -->
{% block content %}



 <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Centro De Salud Villa Tunari</h1>
      <p>El Centro de Salud Villa Tunari del Distrito 4, perteneciente a la Red Lotes y Servicios</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">leer mas &raquo;</a></p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">

        <div class='col-sm-4 col-xs-12 pull-right'>
	    	<p class='text-aline-center'><h2>{{ titulo }}</h2></p>


            {% block login %}
                <h3>Si desear ver tu historial escanea el :</h3>
                {% if paciente %}
                {% for paciente in paciente %}

                    <table class="table table-bordered" style="text-align: center">
                        <thead >
                            <tr>
                                <td>CODIGO QR</td>
                            </tr>
                        </thead>
                        <tbody class="text-aline-center">
                            <tr>
                                <td>  <img src="{{ paciente.codigoqr.url }}" style="width: 200px"></td>
                            </tr>
                            <tr>
                                <td><a class="btn btn-primary" href="/logout/" role="button">Cerrar Sesion</a></td>
                            </tr>
                            <tr>
                                <td><a class="btn btn-primary" href="{% url 'historial:informe_paciente' paciente.ci%}" role="button">Ver historial</a></td>
                            </tr>
                        </tbody>
                    </table>
                {% endfor %}
                {% endif %}


            {% endblock %}

        </div>
       <div class="col-md-4">



        <h2>Informacion</h2>
        <img class="img-responsive" src="{% static 'img/centro1.jpg' %}" style="width: 300px">
        <p>Centro de Salud de Villa Tunari recibe donación de equipos para prevenir el cáncer de cuello uterino. </p>
        <p><a class="btn btn-secondary" href="http://amibolivia.com/AMI/?p=6149" role="button">Leer mas &raquo;</a></p>
      </div>

    <div class="col-md-4">
        <h2>Centro de Salud </h2>
        <img class="img-responsive" src="{% static 'img/exterior.jpg' %}" style="width: 300px">
        <p>parte exterior del centor de salud</p>
        <p><a class="btn btn-secondary" href="#" role="button">Ver detalles &raquo;</a></p>
      </div>


    </div>

    <div class="row">
    <div class="col-md-4">
        <h2>Ambientes</h2>
        <img class="img-responsive" src="{% static 'img/centro2.jpg' %}" style="width: 300px">
        <p>el centro de salud cuenta con diferentes Ambientes</p>
        <p><a class="btn btn-secondary" href="#" role="button">Ver detaller &raquo;</a></p>
      </div>

  <div class="col-md-4">
        <h2>Ambientes</h2>
        <img class="img-responsive" src="{% static 'img/centro3.jpg' %}" style="width: 300px">
        <p>el centro de salud cuenta con diferentes Ambientes</p>
        <p><a class="btn btn-secondary" href="#" role="button">Ver detalles &raquo;</a></p>
      </div>

   <div class="col-md-4">
        <h2>Aviso</h2>
        <img class="img-responsive" src="{% static 'img/aviso.jpg' %}" style="width: 300px">
        <p> el centro de salud informa </p>
        <p><a class="btn btn-secondary" href="#" role="button">Ver detalles &raquo;</a></p>
      </div>
    </div>

  </div>
{% endblock %}

templates/registrar.html
{% extends "base0.html" %}
{% block content %}
    {{ titulo }}
<div class="container">
    <h4 align="CENTER">AGREGAR PACIENTE</h4>

    <form method="POST" cenctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Guardar</button>
    </form>

</div>
{% endblock %}